#!/bin/bash
# See https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8
# See https://github.com/Santulator/Santulator/blob/1.1.0/package/PACKAGING.md

set -e
APP_HOME="$(dirname "$(realpath $0)")"
TARGET="$APP_HOME/target"
DIST="$APP_HOME/dist"
PACKAGE="$TARGET/package"
JAR_FILE="$TARGET/r8bemu.jar"

# Compile
rm -Rf "$TARGET"
javac -d "$TARGET/classes" $(find $APP_HOME/src -name '*.java')
jar --create \
  --file "$JAR_FILE" \
  --main-class com.joprovost.r8bemu.R8BEmu \
  -C "$TARGET/classes" com \
  -C "$APP_HOME/resources" images \
  -C "$APP_HOME/resources" template

# Package
VERSION="0.0.0-$(git show --format="%h" --no-patch)"
mkdir -p "$PACKAGE"
cp "$JAR_FILE" "$PACKAGE"

case $(uname) in
  Darwin)
    jpackage \
      --name R8BEmu \
      --main-jar r8bemu.jar \
      --main-class com.joprovost.r8bemu.R8BEmu \
      --app-version "$VERSION" \
      --input "$PACKAGE" \
      --dest "$DIST" \
      --icon "$APP_HOME/resources/images/logo.icns"
    ;;
  Linux)
    jpackage \
      --name R8BEmu \
      --main-jar r8bemu.jar \
      --main-class com.joprovost.r8bemu.R8BEmu \
      --app-version "$VERSION" \
      --input "$PACKAGE" \
      --dest "$DIST" \
      --icon "$APP_HOME/resources/images/logo_128x128.png" \
      --linux-menu-group "Emulator" \
      --linux-shortcut
    ;;
esac
