#!/bin/bash
function cleanup() { stty cooked echo 2>/dev/null || true; }
trap cleanup EXIT

set -e
cd "$(dirname "$(realpath $0)")"

clear
stty raw -echo

if [ -n "${1:-}" ]; then
  ./r8bemu --interface terminal --playback "./cassette/$1.wav" --script "./script/$1.bas"
else
  ./r8bemu --interface terminal
fi
